config/routes.rb
Camp::Application.routes.draw do
  resources :produtos

  resources :items

  resources :pedidos

  resources :pagamentos

  resources :enderecos

  resources :administradors

  resources :clientes
  
  root :to => "indices#index"
  
  match "/login" => "indices#login"
  match "/alimentos" => "indices#alimento"
  match "/medicamentos" => "indices#medicamento"
  match "/acessorios" => "indices#acessorio"
  
  match "/dados_cliente" => "clientes#show"
  
  match "/dados_admin" => "administradors#show"
  
  match "/autenticacao" => "indices#autenticacao"
  match "/sair" => "indices#logout"
  
  match "/add_cart/:id" => "items#addProduct"
  match "/addEndereco" => "pedidos#addEndereco"
  match "/addIdEndereco/:id" => "pedidos#addIdEndereco"
  

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	
	has_many :pedidos
    has_many :enderecos

	validates_presence_of :nome, :cpf, :identidade, :email, :sexo, :telefone, :senha, :message=> " - é obrigatório!"
	validates_length_of :senha, :in => 6..20, :message => " - deve ter entre 6 e 20 caracteres!"
	validates_confirmation_of :senha, :message=>" - as senhas não conferem! "
	validates_presence_of :senha_confirmation, :message=> " - é obrigatório!"
	validates_numericality_of :cpf, :identidade, :telefone, :only_integer => true, :message=> " - apenas use números!"
	validates_uniqueness_of :email, :cpf, :identidade, :message => " - já existe cliente cadastrado com este valor!"
	
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_filter :verificar_cliente, :only => [:edit, :update, :show]
  before_filter :verificar_administrador, :only => [:index, :destroy]
  
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(session[:usuario_id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(session[:usuario_id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])
	
    respond_to do |format|
      if @cliente.save
	    
        format.html { redirect_to "/autenticacao", notice: 'Você foi cadastrado com sucesso' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to "/dados", notice: 'Suas informações foram alteradas com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div align='center'>  
		<div id="error_explanation" align='center'>
			<h2><%= pluralize(@cliente.errors.count, "erros") %> impediram que o cliente fosse salvo:</h2>

			<ul>
				<% @cliente.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>	
  <% end %>
	
  <br />	
  <div class="field" align='center'>
    <div id='nome_form_campo'><%= f.label :nome, "Nome - " %></div>
    <%= f.text_field :nome, :maxlength => 25 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :cpf, "CPF (somente números) - " %></div>
    <%= f.text_field :cpf, :maxlength => 11 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :identidade, "Identidade (somente números) - " %></div>
    <%= f.text_field :identidade, :maxlength => 9 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :sexo, "Sexo - " %></div>
    <%= f.select :sexo, ([["Masculino","masculino"],["Feminino","feminino"]]) %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :data_nasc, "Data de nascimento - " %></div>
    <%= f.date_select :data_nasc, :start_year=> 1920, end_year: 2002, order: [:day,:month,:year], use_month_names: ["Janeiro","Fevereiro","Marco","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]  %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :telefone, "Telefone (somente números) - " %></div>
    <%= f.text_field :telefone, :maxlength => 10 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :email, "E-mail - " %></div>
    <%= f.text_field :email, :maxlength => 25 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :senha, "Senha - " %></div>
    <%= f.password_field :senha, :size => 10 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :senha, "Confirmação da senha - " %></div>
    <%= f.password_field :senha_confirmation, :size => 10 %>
  </div>
  <div class="actions">
    <input type='submit' value="Enviar" />
  </div>
<% end %>

app/views/clientes/edit.html.erb
<br />
<br />
<font id='titulo_form'>Edição de suas informações:</font>
<br />
<br />
<br />
<div id='dados' align='center'>
	<br />
	<%= render 'form' %>

	<%= link_to 'Voltar para meus dados', "/dados_cliente" %>
	<br />
	<br />
</div>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Cpf</th>
    <th>Identidade</th>
    <th>Sexo</th>
    <th>Data nasc</th>
    <th>Telefone</th>
    <th>Email</th>
    <th>Senha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.cpf %></td>
    <td><%= cliente.identidade %></td>
    <td><%= cliente.sexo %></td>
    <td><%= cliente.data_nasc %></td>
    <td><%= cliente.telefone %></td>
    <td><%= cliente.email %></td>
    <td><%= cliente.senha %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<br />
<br />
<font id='titulo_form'>Cadastro de um novo cliente:</font>
<br />
<br />
<br />
<div id='dados' align='center'>
	<br />
	<%= render 'form' %>

	<%= link_to 'Voltar para login', "/autenticacao" %>
	<br />
	<br />
</div>

app/views/clientes/show.html.erb
<% if flash[:notice]!=nil %>
	<script>alert ('<%= flash[:notice] %>')</script>
<% end %>

<br />
<br />
<font id='titulo_form'>Veja aqui suas informações:</font>
<br />
<br />
<br />

<div id='dados'>
	<p>
	  <b>Nome:</b>
	  <%= @cliente.nome %>

	  <b> | Cpf:</b>
	  <%= @cliente.cpf %>
	</p>

	<p>
	  <b>Identidade:</b>
	  <%= @cliente.identidade %>

	  <b> | Sexo:</b>
	  <%= @cliente.sexo %>

	  <b> | Data de nascimento:</b>
	  <%= @cliente.data_nasc %>
	</p>

	<p>
	  <b>Telefone:</b>
	  <%= @cliente.telefone %>

	  <b> | Email:</b>
	  <%= @cliente.email %>

	  <b> | Senha:</b>
	  <%= @cliente.senha %>
	</p>


	<%= link_to 'Editar informações', edit_cliente_path(@cliente) %> |
	<%= link_to 'Ir para página inicial', "/" %>
	<br />
	<br />
</div>

<br />
<br />
<font id='titulo_form'>Veja aqui seus endereços cadastrados:</font>
<br />
<br />

<div class="tabela_consulta" align="center">
	<div class='cabeca'>	
		<table class="cabeca_fixa">
			<tr>
				<th>Nome</th> <th>Cep</th> <th>Logradouro</th>  <th>Número</th> <th>Complemento</th>  <th>Info - referência</th> <th>Bairro</th> <th>Cidade</th> <th>Estado</th>
			</tr>
		</table>
	</div>
	
	<div class="scroll_movel">
		<table>
		<% Endereco.find(:all, :conditions => ["cliente_id=?", session[:usuario_id]]).each do |endereco| %>
			<tr>
				<td><%= endereco.nome %></td>
				<td><%= endereco.cep %></td>
				<td><%= endereco.logradouro %></td>
				<td><%= endereco.numero %></td>
				<td><%= endereco.complemento %></td>
				<td><%= endereco.info_ref %></td>
				<td><%= endereco.bairro %></td>
				<td><%= endereco.cidade %></td>
				<td><%= endereco.estado %></td>
				<td><%= link_to 'Editar', edit_endereco_path(endereco) %></td>
				<td><%= link_to 'Excluir', endereco, confirm: 'Tem certeza que quer excluir este endereço?', method: :delete %></td>
			</tr>
		<% end %>
		
		</table>
	</div>
	
	<br />
	<div align='center'>
		<%= link_to 'Inserir novo endereço', "/enderecos/new" %>
	</div>
	<br />
	
</div>