config/routes.rb
Camp::Application.routes.draw do
  resources :produtos

  resources :items

  resources :pedidos

  resources :pagamentos

  resources :enderecos

  resources :administradors

  resources :clientes
  
  root :to => "indices#index"
  
  match "/login" => "indices#login"
  match "/alimentos" => "indices#alimento"
  match "/medicamentos" => "indices#medicamento"
  match "/acessorios" => "indices#acessorio"
  
  match "/dados_cliente" => "clientes#show"
  
  match "/dados_admin" => "administradors#show"
  
  match "/autenticacao" => "indices#autenticacao"
  match "/sair" => "indices#logout"
  
  match "/add_cart/:id" => "items#addProduct"
  match "/addEndereco" => "pedidos#addEndereco"
  match "/addIdEndereco/:id" => "pedidos#addIdEndereco"
  

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base

    belongs_to :cliente
	belongs_to :endereco
	belongs_to :pagamento
	has_many :items

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  
  before_filter :verificar_administrador,  :only => [:edit]
  before_filter :verificar_tudo, :only => [ :new, :show]
  before_filter :verificar_cliente, :only => [:index, :addEndereco, :addIdEndereco]
  
  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.find(:all, :conditions => ["cliente_id=?", session[:usuario_id]])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pedidos }
    end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/new
  # GET /pedidos/new.json
  def new
    @pedido = Pedido.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/1/edit
  def edit
    @pedido = Pedido.find(params[:id])
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(params[:pedido])

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render json: @pedido, status: :created, location: @pedido }
      else
        format.html { render action: "new" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pedidos/1
  # PUT /pedidos/1.json
  def update
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      if @pedido.update_attributes(params[:pedido])
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido = Pedido.find(params[:id])
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url }
      format.json { head :no_content }
    end
  end
  
  def addEndereco
	@pedido = Pedido.find(session[:pedido_atual])
	if @pedido.items.size==0
		flash[:notice]='Você precisa adicionar pelo menos um produto no pedido!'
		redirect_to "/pedidos"
	else
		
	end
  end
  
  def addIdEndereco
	@pedido = Pedido.find(session[:pedido_atual])
	@pedido.endereco_id=params[:id]
	@pedido.save
	redirect_to "/pagamentos/new"
  end
  
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "erros") %> impediram que este pedido fosse salvo:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id='nome_form_campo'><%= f.label :estado, "Estado - " %></div>
    <%= f.select :estado, ([["Entregando","entregando"],["Fechado","fechado"] ]) %>
  </div>
  
  <div style='display:none'>
	  <div class="field">
		<%= f.label :valor_total %><br />
		<%= f.text_field :valor_total %>
	  </div>
	  
	  <div class="field">
		<%= f.label :cliente_id %><br />
		<%= f.number_field :cliente_id %>
	  </div>
	  <div class="field">
		<%= f.label :endereco_id %><br />
		<%= f.number_field :endereco_id %>
	  </div>
	  <div class="field">
		<%= f.label :pagamento_id %><br />
		<%= f.number_field :pagamento_id %>
	  </div>
  </div>
  
  <div class="actions">
    <input type='submit' value="Enviar" />
  </div>
<% end %>

app/views/pedidos/addEndereco.html.erb
<br />
<br />
<font id='titulo_form'>Escolha aqui o endereco:</font>
<br />
<br />

<div class="tabela_consulta" align="center">
	<div class='cabeca'>	
		<table class="cabeca_fixa">
			<tr>
				<th>Nome</th> <th>Cep</th> <th>Logradouro</th>  <th>Número</th> <th>Complemento</th>  <th>Info - referência</th> <th>Bairro</th> <th>Cidade</th> <th>Estado</th>
			</tr>
		</table>
	</div>
	
	<div class="scroll_movel">
		<table>
		<% Endereco.find(:all, :conditions => ["cliente_id=?", session[:usuario_id]]).each do |endereco| %>
			<tr>
				<td><%= endereco.nome %></td>
				<td><%= endereco.cep %></td>
				<td><%= endereco.logradouro %></td>
				<td><%= endereco.numero %></td>
				<td><%= endereco.complemento %></td>
				<td><%= endereco.info_ref %></td>
				<td><%= endereco.bairro %></td>
				<td><%= endereco.cidade %></td>
				<td><%= endereco.estado %></td>
				<td><%= link_to 'Por este no pedido', "/addIdEndereco/#{endereco.id}" %></td>
			</tr>
		<% end %>
		
		</table>
	</div>
	
	<br />
	<br />
	<div align='center'><%= link_to 'Voltar para pedidos', "/pedidos" %></div>
	<br />
	<br />

</div>

app/views/pedidos/edit.html.erb
<br />
<br />
<font id='titulo_form'>Atualizar o status do pedido do cliente:</font>
<br />
<br />
<br />
<div id='dados' align='center'>
	<br />
	<%= render 'form' %>

	<%= link_to 'Página inicial', "/" %>
	<br />
	<br />
</div>

app/views/pedidos/index.html.erb
<% if flash[:notice]!=nil %>
	<script>alert ('<%= flash[:notice] %>')</script>
<% end %>

<% if session[:tipo_user]=='cliente' %>
	<div id='lista_pedidos' align='center'>
		<br />
		<br />
		<font id='titulo_form'>Busque seus pedidos pelos seus estados:</font>
		<br />
		<br />
		<br />
		
		<div id='menu_estado' >
			<font style='float:left' color='#fff'>_________</font>
		    <div style='float:left'><a href='javascript:void(0)' onClick="mostra_pedido_byEstado('aberto')">Aberto</a></div>
			
			<font style='float:left' color='#fff'>_________</font>
			<div style='float:left'><a href='javascript:void(0)' onClick="mostra_pedido_byEstado('pagando')">Pagando</a></div>
			
			<font style='float:left' color='#fff'>_________</font>
			<div style='float:left'><a href='javascript:void(0)' onClick="mostra_pedido_byEstado('entregando')">Entregando</a></div>
			
			<font style='float:left' color='#fff'>_________</font>
			<div style='float:left'><a href='javascript:void(0)' onClick="mostra_pedido_byEstado('fechado')">Fechado</a></div>
			
			<font style='float:left' color='#fff'>_________</font>
			<div style='float:left'><a href='javascript:void(0)' onClick="mostra_pedido_byEstado('all_orders')">Ver todos</a></div>
			
		</div>
		
		<br />
		<br />
		<br />
		<br />
		
		<div id='all_orders' align='center' style=''>
			<font id='titulo_form'>Todos os pedidos:</font>
			<br />
			<br />

			<div class='area_pedidos'>
					<% @pedidos.each do |pedido| %>
						<div id='linha'>
							<div id='coluna_pedido'>Número do pedido: <%= pedido.id %></div>
							<div id='coluna_pedido'>Data: <%= pedido.created_at %></div>
							<div id='coluna_pedido'>Estágio: <%= pedido.estado %></div>
							
							<% valor_tot=0 %>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<% valor_tot+=Produto.find(item.produto_id).preco*item.quantidade %>
							<% end %>
							<div id='coluna_pedido'>Total: R$ <%= valor_tot %></div>
							
						</div>
						
						<div id='itens' >
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<div id='linha'>
									<div id='coluna_comum'>Nome do produto: <%= Produto.find(item.produto_id).nome %></div>
									<div id='coluna_comum'>Quantidade: <%= item.quantidade %></div>
									<div id='coluna_comum'>Sub-valor: <%= Produto.find(item.produto_id).preco*item.quantidade %></div>
									<% if pedido.estado=='aberto' %>
										<div id='coluna_comum'><%= link_to 'Editar', edit_item_path(item) %></div>
										<div id='coluna_comum'><%= link_to 'Excluir', item, confirm: 'Tem certeza que quer excluir este item?', method: :delete %></div>
									<% end %>
								</div>
							<% end %>	
						</div>
					<% end %>
					
				
				<br />
			</div>
		</div>	
		
		
		<br />
		<br />
		<br />
		
		
		<div id='aberto' align='center' style='display:none'>
			<font id='titulo_form'>Pedidos em aberto:</font>
			<br />
			<br />

			<div class='area_pedidos'>
					<% Pedido.find(:all, :conditions => ["estado='aberto' and cliente_id=?", session[:usuario_id]]).each do |pedido| %>
						<div id='linha'>
							<div id='coluna_pedido'>Número do pedido: <%= pedido.id %></div>
							<div id='coluna_pedido'>Data: <%= pedido.created_at %></div>
							
							<% valor_tot=0 %>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<% valor_tot+=Produto.find(item.produto_id).preco*item.quantidade %>
							<% end %>
							<div id='coluna_pedido'>Total: R$ <%= valor_tot %></div>
							<div id='coluna_pedido'><%= link_to 'Finalizar', "/addEndereco" %></div>
						</div>
						
						<div id='itens'>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<div id='linha'>
									<div id='coluna_comum'>Nome do produto: <%= Produto.find(item.produto_id).nome %></div>
									<div id='coluna_comum'>Quantidade: <%= item.quantidade %></div>
									<div id='coluna_comum'>Sub-valor: <%= Produto.find(item.produto_id).preco*item.quantidade %></div>
									<div id='coluna_comum'><%= link_to 'Editar', edit_item_path(item) %></div>
									<div id='coluna_comum'><%= link_to 'Excluir', item, confirm: 'Tem certeza que quer excluir este item?', method: :delete %></div>
								</div>
							<% end %>	
						</div>
					
					<% end %>
					
				<br />
			</div>
			
		</div>
		
		
		<div id='pagando' align='center' style='display:none'>
			<font id='titulo_form'>Pedidos em processo de pagamento:</font>
			<br />
			<br />

			<div class='area_pedidos'>
					<% Pedido.find(:all, :conditions => ["estado='pagando' and cliente_id=?", session[:usuario_id]]).each do |pedido| %>
						<div id='linha'>
							<div id='coluna_pedido'>Número do pedido: <%= pedido.id %></div>
							<div id='coluna_pedido'>Data: <%= pedido.created_at %></div>
							
							<% valor_tot=0 %>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<% valor_tot+=Produto.find(item.produto_id).preco*item.quantidade %>
							<% end %>
							<div id='coluna_pedido'>Total: R$ <%= valor_tot %></div>
						</div>
							
						<div id='itens'>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<div id='linha'>
									<div id='coluna_comum'>Nome do produto: <%= Produto.find(item.produto_id).nome %></div>
									<div id='coluna_comum'>Quantidade: <%= item.quantidade %></div>
									<div id='coluna_comum'>Sub-valor: <%= Produto.find(item.produto_id).preco*item.quantidade %></div>
								</div>
							<% end %>	
						</div>
						
					<% end %>
					
				<br />
			</div>
			
		</div>
		
		<div id='entregando' align='center' style='display:none'>
			<font id='titulo_form'>Pedidos em processo de entrega:</font>
			<br />
			<br />

			<div class='area_pedidos'>
					<% Pedido.find(:all, :conditions => ["estado='entregando'  and cliente_id=?", session[:usuario_id]]).each do |pedido| %>
						<div id='linha'>
							<div id='coluna_pedido'>Número do pedido: <%= pedido.id %></div>
							<div id='coluna_pedido'>Data: <%= pedido.created_at %></div>
							
							<% valor_tot=0 %>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<% valor_tot+=Produto.find(item.produto_id).preco*item.quantidade %>
							<% end %>
							<div id='coluna_pedido'>Total: R$ <%= valor_tot %></div>
						</div>
							
						<div id='itens'>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<div id='linha'>
									<div id='coluna_comum'>Nome do produto: <%= Produto.find(item.produto_id).nome %></div>
									<div id='coluna_comum'>Quantidade: <%= item.quantidade %></div>
									<div id='coluna_comum'>Sub-valor: <%= Produto.find(item.produto_id).preco*item.quantidade %></div>
								</div>
							<% end %>	
						</div>
						
					<% end %>
				<br />
			</div>
			
		</div>
		
		<div id='fechado' align='center' style='display:none'>
			<font id='titulo_form'>Pedidos completos entregues:</font>
			<br />
			<br />

			<div class='area_pedidos'>
					<% Pedido.find(:all, :conditions => ["estado='fechado' and cliente_id=?", session[:usuario_id]]).each do |pedido| %>
						<div id='linha'>
							<div id='coluna_pedido'>Número do pedido: <%= pedido.id %></div>
							<div id='coluna_pedido'>Data: <%= pedido.created_at %></div>
							
							<% valor_tot=0 %>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<% valor_tot+=Produto.find(item.produto_id).preco*item.quantidade %>
							<% end %>
							<div id='coluna_pedido'>Total: R$ <%= valor_tot %></div>
						</div>
							
						<div id='itens'>
							<% Item.find(:all, :conditions => ["pedido_id=?", pedido.id]).each do |item| %>
								<div id='linha'>
									<div id='coluna_comum'>Nome do produto: <%= Produto.find(item.produto_id).nome %></div>
									<div id='coluna_comum'>Quantidade: <%= item.quantidade %></div>
									<div id='coluna_comum'>Sub-valor: <%= Produto.find(item.produto_id).preco*item.quantidade %></div>
								</div>
							<% end %>	
						</div>
						
					<% end %>
				<br />
			</div>
			
		</div>
		<!---->
		<br />
		<br />
		<br />
		<br />
		
	</div>
<% else %>
	<% if session[:tipo_user]=='admin' %>
	
	<% end %>

<% end %>
	
<!--
<%= link_to 'New Pedido', new_pedido_path %>-->

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Valor total:</b>
  <%= @pedido.valor_total %>
</p>

<p>
  <b>Estado:</b>
  <%= @pedido.estado %>
</p>

<p>
  <b>Cliente:</b>
  <%= @pedido.cliente_id %>
</p>

<p>
  <b>Endereco:</b>
  <%= @pedido.endereco_id %>
</p>

<p>
  <b>Pagamento:</b>
  <%= @pedido.pagamento_id %>
</p>


<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>