config/routes.rb
Camp::Application.routes.draw do
  resources :produtos

  resources :items

  resources :pedidos

  resources :pagamentos

  resources :enderecos

  resources :administradors

  resources :clientes
  
  root :to => "indices#index"
  
  match "/login" => "indices#login"
  match "/alimentos" => "indices#alimento"
  match "/medicamentos" => "indices#medicamento"
  match "/acessorios" => "indices#acessorio"
  
  match "/dados_cliente" => "clientes#show"
  
  match "/dados_admin" => "administradors#show"
  
  match "/autenticacao" => "indices#autenticacao"
  match "/sair" => "indices#logout"
  
  match "/add_cart/:id" => "items#addProduct"
  match "/addEndereco" => "pedidos#addEndereco"
  match "/addIdEndereco/:id" => "pedidos#addIdEndereco"
  

end

app/models/produto.rb
class Produto < ActiveRecord::Base

    has_many :items
	
	validates_presence_of :nome, :preco, :descricao, :quant_esto, :message=> " - é obrigatório!"
	validates_numericality_of :preco, :message=> " - deve ser um número."
	validates_numericality_of :quant_esto, :only_integer=> true, :message=> " - deve ser um número inteiro."
	
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  
  before_filter :verificar_administrador, :only => [:index, :destroy, :edit, :new]
  
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
	
	@produto = Produto.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to "/", notice: 'O produto foi criado com sucesso.' }
        #format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to "/", notice: 'O produto foi editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "erros") %> impediram que este produto fosse salvo:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id='nome_form_campo'><%= f.label :nome, "Nome - " %></div>
    <%= f.text_field :nome, :maxlength => 15 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :preco, "Preço - " %></div>
    <%= f.text_field :preco, :maxlength => 6 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :descricao, "Descrição - " %></div>
    <%= f.text_field :descricao, :maxlength => 25 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :quant_esto, "Quantidade em estoque - " %></div>
    <%= f.number_field :quant_esto, :maxlength => 6 %>
  </div>
  <div class="field">
    <div id='nome_form_campo'><%= f.label :tipo_prod, "Tipo de produto - " %></div>
    <select id='produto_tipo_prod' name='produto[tipo_prod]' onchange="troca_campos()">	
		<option value='alimento'  >Alimento</option>
		<option value='medicamento'  >Medicamento</option>
		<option value='acessorio'  >Acessório</option>
	</select>
	
  </div>
  <div id='ali' style=''>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :marca, "Marca (Whiskas) - " %></div>
		<%= f.text_field :marca %>
	  </div>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :peso, "Peso - " %></div>
		<%= f.text_field :peso %>
	  </div>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :tipo_animal, "Tipo de animal - " %></div>
		<%= f.text_field :tipo_animal %>
	  </div>
  </div>	
  
  <div id='med' style='display:none'>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :tipo_med, "Tipo de medicamento - " %></div>
		<%= f.text_field :tipo_med %>
	  </div>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :dosagem, "Dosagem (ex. 100 ml) - " %></div>
		<%= f.text_field :dosagem %>
	  </div>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :tipo_adm, "Modo de administração (ex. injetável) - " %></div>
		<%= f.text_field :tipo_adm %>
	  </div>
  </div>
  
  <div id='ace' style='display:none'>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :tamanho, "Tamanho em cm (ex. 40x20x50 (LxAxC)) - " %></div>
		<%= f.text_field :tamanho %>
	  </div>
	  <div class="field">
		<div id='nome_form_campo'><%= f.label :tipo_ace, "Tipo (ex. casinha) - " %></div>
		<%= f.text_field :tipo_ace %>
	  </div>
  </div>
  
  <div class="actions">
    <input type="submit" value="Enviar" />
  </div>
<% end %>

app/views/produtos/edit.html.erb
<br />
<br />
<font id='titulo_form'>Edição dos dados deste produto:</font>
<br />
<br />
<br />
<div id='dados' align='center'>
	<br />
	<%= render 'form' %>

	<%= link_to 'Voltar para todos os produtos', "/produtos" %>
	<br />
	<br />
</div>

app/views/produtos/index.html.erb
<!-- ......................................................Alimento................................................ -->

<br />
<br />
<font id='titulo_form'>Ver todos os produtos do tipo alimento:</font>
<br />
<br />
<br />

<div class="tabela_consulta" align="center">
	<div class='cabeca'>	
		<table class="cabeca_fixa">
			<tr>
				<th>Nome</th> <th>Preço</th> <th>Descrição</th>  <th>Quantidade em estoque</th> <th>Tipo de produto</th>  <th>Marca</th> <th>Peso</th> <th>Tipo de animal</th>
			</tr>
		</table>
	</div>
	
	<div class="scroll_movel">
	
		<table>
  
			<% Produto.find(:all, :conditions => ["tipo_prod='alimento'"]).each do |produto| %>
				<tr>
					<td><%= produto.nome %></td>
					<td><%= produto.preco %></td>
					<td><%= produto.descricao %></td>
					<td><%= produto.quant_esto %></td>
					<td><%= produto.tipo_prod %></td>
					<td><%= produto.marca %></td>
					<td><%= produto.peso %></td>
					<td><%= produto.tipo_animal %></td>
					<td><%= link_to 'Visualizar', produto %></td>
					<td><%= link_to 'Editar', edit_produto_path(produto) %></td>
					<td><%= link_to 'Excluir', produto, confirm: 'Tens certeza que deseja excluir este alimento?', method: :delete %></td>
				</tr>
			<% end %>
		</table>
	</div>
	
	<br />
	<br />
	<br />

</div>

<!-- ......................................................Medicamento................................................ -->

<br />
<br />
<font id='titulo_form'>Ver todos os produtos do tipo medicamento:</font>
<br />
<br />
<br />

<div class="tabela_consulta" align="center">
	<div class='cabeca'>	
		<table class="cabeca_fixa">
			<tr>
				<th>Nome</th> <th>Preço</th> <th>Descrição</th>  <th>Quantidade em estoque</th> <th>Tipo de produto</th>  <th>Tipo de medicamento</th> <th>Dosagem</th> <th>Modo de administração</th>
			</tr>
		</table>
	</div>
	
	<div class="scroll_movel">
	
		<table>
  
			<% Produto.find(:all, :conditions => ["tipo_prod='medicamento'"]).each do |produto| %>
				<tr>
					<td><%= produto.nome %></td>
					<td><%= produto.preco %></td>
					<td><%= produto.descricao %></td>
					<td><%= produto.quant_esto %></td>
					<td><%= produto.tipo_prod %></td>
					<td><%= produto.tipo_med %></td>
					<td><%= produto.dosagem %></td>
					<td><%= produto.tipo_adm %></td>
					<td><%= link_to 'Visualizar', produto %></td>
					<td><%= link_to 'Editar', edit_produto_path(produto) %></td>
					<td><%= link_to 'Excluir', produto, confirm: 'Tens certeza que deseja excluir este medicamento?', method: :delete %></td>
				</tr>
			<% end %>
		</table>
	</div>
	
	<br />
	<br />
	<br />

</div>

<!-- ......................................................Acessório................................................ -->

<br />
<br />
<font id='titulo_form'>Ver todos os produtos do tipo acessório:</font>
<br />
<br />
<br />

<div class="tabela_consulta" align="center">
	<div class='cabeca'>	
		<table class="cabeca_fixa">
			<tr>
				<th>Nome</th> <th>Preço</th> <th>Descrição</th>  <th>Quantidade em estoque</th> <th>Tipo de produto</th>  <th>Tamanho</th> <th>Tipo do acessório</th> 
			</tr>
		</table>
	</div>
	
	<div class="scroll_movel">
	
		<table>
  
			<% Produto.find(:all, :conditions => ["tipo_prod='acessorio'"]).each do |produto| %>
				<tr>
					<td><%= produto.nome %></td>
					<td><%= produto.preco %></td>
					<td><%= produto.descricao %></td>
					<td><%= produto.quant_esto %></td>
					<td><%= produto.tipo_prod %></td>
					<td><%= produto.tamanho %></td>
					<td><%= produto.tipo_ace %></td>
					<td><%= link_to 'Visualizar', produto %></td>
					<td><%= link_to 'Editar', edit_produto_path(produto) %></td>
					<td><%= link_to 'Excluir', produto, confirm: 'Tens certeza que deseja excluir este acessório?', method: :delete %></td>
				</tr>
			<% end %>
		</table>
	</div>
	
	<br />
	<br />
	<br />

</div>

	<br />
	<div align='center'><%= link_to 'Inserir novo produto', new_produto_path %></div>
	<br />
	<br />

app/views/produtos/new.html.erb
<br />
<br />
<font id='titulo_form'>Cadastro de um novo produto:</font>
<br />
<br />
<br />
<div id='dados' align='center'>
	<br />
	<%= render 'form' %>

	<%= link_to 'Voltar para produtos', "/produtos" %>
	<br />
	<br />
</div>

app/views/produtos/show.html.erb
<% if flash[:notice]!=nil %>
	<script>alert ('<%= flash[:notice] %>')</script>
<% end %>

<br />
<br />
<font id='titulo_form'>Veja as informações deste produto:</font>
<br />
<br />
<br />

<div id='dados'>

	<p>
	  <b>Nome:</b>
	  <%= @produto.nome %>
	
	  <b> | Preço:</b>
	  <%= @produto.preco %>
	
	  <b> | Descrição:</b>
	  <%= @produto.descricao %>
	</p>

	<p>
	  <b>Quantidade em estoque:</b>
	  <%= @produto.quant_esto %>
	
	  <b> | Tipo de produto:</b>
	  <%= @produto.tipo_prod %>
	</p>
	
	<% if @produto.tipo_prod=='alimento' %> 
		<p>
		  <b>Marca:</b>
		  <%= @produto.marca %>
		
		  <b> | Peso:</b>
		  <%= @produto.peso %>
		
		  <b> | Tipo de animal:</b>
		  <%= @produto.tipo_animal %>
		</p>
	<% end %>
	
	<% if @produto.tipo_prod=='medicamento' %> 
		<p>
		  <b>Tipo med:</b>
		  <%= @produto.tipo_med %>
		
		  <b> | Dosagem:</b>
		  <%= @produto.dosagem %>
		
		  <b> | Modo de administração:</b>
		  <%= @produto.tipo_adm %>
		</p>
	<% end %>
	
	<% if @produto.tipo_prod=='acessorio' %>
		<p>
		  <b>Tamanho:</b>
		  <%= @produto.tamanho %>
		</p>

		<p>
		  <b>Tipo ace:</b>
		  <%= @produto.tipo_ace %>
		</p>
	<% end %>

	<%= link_to 'Editar dados deste produto', edit_produto_path(@produto) %> |
	<%= link_to 'Voltar para todos os produtos', produtos_path %>
	<br />
	<br />
</div>