config/routes.rb
Camp::Application.routes.draw do
  resources :produtos

  resources :items

  resources :pedidos

  resources :pagamentos

  resources :enderecos

  resources :administradors

  resources :clientes
  
  root :to => "indices#index"
  
  match "/login" => "indices#login"
  match "/alimentos" => "indices#alimento"
  match "/medicamentos" => "indices#medicamento"
  match "/acessorios" => "indices#acessorio"
  
  match "/dados_cliente" => "clientes#show"
  
  match "/dados_admin" => "administradors#show"
  
  match "/autenticacao" => "indices#autenticacao"
  match "/sair" => "indices#logout"
  
  match "/add_cart/:id" => "items#addProduct"
  match "/addEndereco" => "pedidos#addEndereco"
  match "/addIdEndereco/:id" => "pedidos#addIdEndereco"
  

end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base

    belongs_to :pedido

end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  
  before_filter :verificar_cliente, :only => [ :new, :edit]
  before_filter :verificar_administrador, :only => [:index]
  
  # GET /pagamentos
  # GET /pagamentos.json
  def index
    @pagamentos = Pagamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pagamentos }
    end
  end

  # GET /pagamentos/1
  # GET /pagamentos/1.json
  def show
    @pagamento = Pagamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pagamento }
    end
  end

  # GET /pagamentos/new
  # GET /pagamentos/new.json
  def new
    @pagamento = Pagamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pagamento }
    end
  end

  # GET /pagamentos/1/edit
  def edit
    @pagamento = Pagamento.find(params[:id])
  end

  # POST /pagamentos
  # POST /pagamentos.json
  def create
    @pagamento = Pagamento.new(params[:pagamento])
	@pagamento.pedido_id=session[:pedido_atual]
	
	respond_to do |format|
      if @pagamento.save
		p = Pedido.find(session[:pedido_atual])
		p.pagamento_id=@pagamento.id
		p.estado="pagando"
		p.save
		
		p2 = Pedido.new
		p2.estado="aberto"
		p2.cliente_id=session[:usuario_id]
		p2.save
		session[:pedido_atual]=p2.id
		
        format.html { redirect_to "/pedidos", notice: 'Seu pedido foi finalizado, acompanhe-o no seu quadro de pedidos. Aguardamos a confirmação deste pagamento. \nO número dele é ' + p.id + '.' }
        format.json { render json: @pagamento, status: :created, location: @pagamento }
      else
        format.html { render action: "new" }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pagamentos/1
  # PUT /pagamentos/1.json
  def update
    @pagamento = Pagamento.find(params[:id])

    respond_to do |format|
      if @pagamento.update_attributes(params[:pagamento])
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.json
  def destroy
    @pagamento = Pagamento.find(params[:id])
    @pagamento.destroy

    respond_to do |format|
      format.html { redirect_to pagamentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/views/pagamentos/_form.html.erb
<%= form_for(@pagamento) do |f| %>
  <% if @pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagamento.errors.count, "erros") %> impediram que os dados do pagamento fossem salvos :</h2>

      <ul>
      <% @pagamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<div id='nome_form_campo'><%= f.label :tipo, "Tipo de pagamento - " %></div>
		<input type='radio' id='pagamento_tipo' name='pagamento[tipo]' value='boleto' checked onClick="showDiv('cartao_cre', false); showDiv('cartao_deb', false);" /> Boleto bancário
		<input type='radio' id='pagamento_tipo' name='pagamento[tipo]' value='cartao_credito' onClick="showDiv('cartao_cre', true); showDiv('cartao_deb', true);" /> Cartão de crédito
		<input type='radio' id='pagamento_tipo' name='pagamento[tipo]' value='cartao_debito' onClick="showDiv('cartao_cre', false); showDiv('cartao_deb', true);" /> Cartão de dédito
	</div>
  
	<div id='cartao_deb'>
		<div class="field">
			<div id='nome_form_campo'><%= f.label :bandeira_card, "Bandeira do cartão - " %></div>
			<%= f.select :bandeira_card, ([["Master Card","master_card"],["Visa","visa"], ["American Express","american_express"] ]) %>
		</div>
		
		<div class="field">
			<div id='nome_form_campo'><%= f.label :nome_card, "Nome impresso no cartão - " %></div>
			<%= f.text_field :nome_card, :maxlength => 25 %>
		</div>
		
		<div class="field">
			<div id='nome_form_campo'><%= f.label :numero_card, "Número do cartão (use apenas números) - " %></div>
			<%= f.text_field :numero_card, :maxlength => 16, :size=> 16 %>
		</div>
	  
		<div class="field">
			<div id='nome_form_campo'><%= f.label :validade_card, "Validade do cartão (ex. 05/2014) - " %></div>
			<%= f.text_field :validade_card, :maxlength => 7, :size=> 7 %>
		</div>
	  
		<div class="field">
			<div id='nome_form_campo'><%= f.label :codSecure_card, "Código de segurança (veja atrás) - " %></div>
			<%= f.text_field :codSecure_card, :maxlength => 3, :size=> 3 %>
		</div>
	</div>
	
	<div id='cartao_cre'>
		<div class="field">
			<div id='nome_form_campo'><%= f.label :num_parcela_card, "Número de parcelas: " %></div>
			<%= f.select :num_parcela_card , ([["1","1"],["2","2"], ["3","3"], ["4","4"] ]) %>
		</div>
	</div>
	
    <div class="actions">
		<input type='submit' value="Enviar" />
    </div>
	
<% end %>

app/views/pagamentos/index.html.erb
<h1>Listing pagamentos</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th>Bandeira card</th>
    <th>Nome card</th>
    <th>Numero card</th>
    <th>Validade card</th>
    <th>Codsecure card</th>
    <th>Num parcela card</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pagamentos.each do |pagamento| %>
  <tr>
    <td><%= pagamento.tipo %></td>
    <td><%= pagamento.bandeira_card %></td>
    <td><%= pagamento.nome_card %></td>
    <td><%= pagamento.numero_card %></td>
    <td><%= pagamento.validade_card %></td>
    <td><%= pagamento.codSecure_card %></td>
    <td><%= pagamento.num_parcela_card %></td>
    <td><%= link_to 'Show', pagamento %></td>
    <td><%= link_to 'Edit', edit_pagamento_path(pagamento) %></td>
    <td><%= link_to 'Destroy', pagamento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pagamento', new_pagamento_path %>

app/views/pagamentos/new.html.erb
<% if flash[:notice]!=nil %>
	<script>alert ('<%= flash[:notice] %>')</script>
<% end %>

<br />
<br />
<font id='titulo_form'>Preencha os dados para efetuar o pagamento:</font>
<br />
<br />
<br />
<div id='dados' align='center'>
	<br />
	<%= render 'form' %>

	<%= link_to 'Ir para pedidos', "/pedidos" %>
	<br />
</div>

app/views/pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @pagamento.tipo %>
</p>

<p>
  <b>Bandeira card:</b>
  <%= @pagamento.bandeira_card %>
</p>

<p>
  <b>Nome card:</b>
  <%= @pagamento.nome_card %>
</p>

<p>
  <b>Numero card:</b>
  <%= @pagamento.numero_card %>
</p>

<p>
  <b>Validade card:</b>
  <%= @pagamento.validade_card %>
</p>

<p>
  <b>Codsecure card:</b>
  <%= @pagamento.codSecure_card %>
</p>

<p>
  <b>Num parcela card:</b>
  <%= @pagamento.num_parcela_card %>
</p>


<%= link_to 'Edit', edit_pagamento_path(@pagamento) %> |
<%= link_to 'Back', pagamentos_path %>